name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs:
      is_release:
        description: Should this be a release package (rather than preview)
        required: true
        default: 'false'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Get timestamp
      uses: 1466587594/get-current-time@v1
      id: current-time
      with:
        format: YYYYMMDD-HHmmSS
    
    - name: Pack Preview
      run: dotnet pack SpanLinq/SpanLinq.csproj -c Release --include-source -o out --version-suffix "CI-${{ steps.current-time.outputs.formattedTime }}"
      if: github.event.inputs.is_release == 'false'
    - name: Pack Release
      run: dotnet pack SpanLinq/SpanLinq.csproj -c Release --include-source -o out
      if: github.event.inputs.is_release == 'true'
      
    - name: Push
      if: ${{ success() && (github.event.inputs.is_release == 'true' || github.event.inputs.is_release == 'false') }}
      run: |
        dotnet nuget push 'out/*.nupkg' -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
